apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sm-mysql-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sm-mysql  # Reemplaza con el nombre de tu Deployment MySQL
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50