apiVersion: v1
kind: Secret
metadata:
        name: sm-mysql-secret
type: Opaque
data:
        sm-mysql-root-pass: cm9vdA==
        sm-mysql-smuser: c211c2Vy
        sm-mysql-smpass: c21wYXNz
        sm-mysql-db: c3R1ZGVudG1hbmFnZW1lbnRkYg==