# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    #config.vm.network "forwarded_port", guest: 8080, host: 8080
    #config.vm.network "public_network"
    config.vm.network "private_network", ip: "192.168.33.12"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    #config.vm.network "private_network", ip: "192.168.50.6"
  
    config.vm.provider "virtualbox" do |vb|
      vb.name = 'vm-tp9'
      vb.memory = "4096"
      vb.cpus = 4
    end
    config.vm.provision "shell", inline: "sudo apt-get update"
    config.vm.provision "shell", path: "provision.sh" # Script de aprovisionamiento para instalar Jenkins y Docker
  end