# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
  
    config.vm.provider "virtualbox" do |vb|
      vb.name = 'vm-tp9'
      vb.memory = "6144"
      vb.cpus = 4
    end
  
    config.vm.provision "shell", inline: <<-SHELL
      # Actualizamos los paquetes
      sudo apt-get update -y
      sudo apt-get upgrade -y
  
      # Instalamos Docker
      sudo apt-get install -y docker.io
      sudo usermod -aG docker vagrant    

      #Instalar snap
      sudo apt-get update
      sudo apt-get install snapd      
      
      # Instalamos kubectl
      #sudo snap install kubectl --classic

      # Instalamos Helm
      sudo snap install helm --classic

      # Instalar Minikube
      MINIKUBE_VERSION="latest"
      curl -LO https://storage.googleapis.com/minikube/releases/${MINIKUBE_VERSION}/minikube_latest_amd64.deb
      sudo dpkg -i minikube_latest_amd64.deb
  
      # Instalar kubectl
      KUBECTL_VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
      curl -LO https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      sudo mv ./kubectl /usr/local/bin/kubectl

      # Instalamos Minikube
      #sudo curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
      #sudo dpkg -i minikube_latest_amd64.deb
      #sudo apt-get install -f
      #sudo usermod -aG minikube vagrant

      # Configuramos Minikube
      #minikube config set vm-driver virtualbox

    SHELL
  end
  